#!/bin/sh
####################
# Car Media Server #
####################

set -e

 
# Exit if device or mountpoint is empty.
test -z "$UM_DEVICE" && test -z "$UM_MOUNTPOINT" && exit 0
 
# get volume label name
label=`blkid -s LABEL -o value $UM_DEVICE`
 

# There is exist bug with the timestamp for mountpoint. There is hot fix
touch $UM_MOUNTPOINT

# Looking for device with the PLEX label. If PLEX label detected then we create symlink
if [ "$label"=='PLEX' ]; then
  ln -sf "$UM_MOUNTPOINT" "/media/PLEX"
fi

exit 0
